name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and start server
        run: |
          npm run build
          pm2 start dist/server.js

      - name: Save server logs
        run: pm2 logs > logs.txt
